### ISSUE TITLE
[HREF] as any type of context in context menu returns only page URL

### ISSUE THREAD

**Issue by cubedj** [andy-portmen/external-application-button#1]
EAB worked fine until yesterday and now everything in context menu for [HREF] returns only url of  the page and for [HOSTNAME] [PATHNAME] [HASH] [PROTOCOL] and [SELECTIONTEXT] it returns UNDEFINED.. I'm not sure if it could be caused by the latest Chrome update (btw. I'm on the dev version) or if I somehow broke it...

**Comment by qwertea** [comment]
Also experiencing this since the last update. It's a real problem. I'm on chrome stable though.

**Comment by raku-cat** [comment]
Can confirm this also happening on firefox beta 57, downgrading to 0.2.1 fixes the isssue.
