### ISSUE TITLE
How to get desktop notification from bash script?

### ISSUE THREAD

**Issue by ZaxonXP** [andy-portmen/external-application-button#103]
Normally when I use `notify-send` from bash script I get a desktop notification.
However, when this extension is used I get no notifications.

Can you add some example on your site how to do it for Linux?

Kind regards,
Piotr

**Comment by andy-portmen** [comment]
Forgotten to add quotes?

Does not work:
![Screenshot 2024-04-29 at 04 49 36](https://github.com/andy-portmen/external-application-button/assets/6779535/0fa6c0bc-0828-4f32-b0bb-662ce85675e6)

Works:
![Screenshot 2024-04-29 at 04 49 56](https://github.com/andy-portmen/external-application-button/assets/6779535/ab9cfec0-94bc-451b-9044-b55ae105ec60)

**Comment by ZaxonXP** [comment]
Somehow it does not work for me. I created a small script like this:
```
#!/bin/bash
d=$(date)
echo "$d $1" >> ~/log.txt
DISPLAY=:0 /usr/bin/notify-send "$1"
```
When I run it from the terminal it creates pop up notification. But when from the extension, then there is not. The script is running because I get entry in the log.txt file, but no pop up. How should I change the script? Or it is something else to change?

**Comment by andy-portmen** [comment]
is `$1` quotation free? Try to run your Chrome in debugging mode and see the output of the script in the console.

https://www.chromium.org/for-testers/enable-logging/

**Comment by ZaxonXP** [comment]
Actually I found some hint from [Dunst](https://dunst-project.org/faq/#sending-notifications-from-another-user-root) help that worked:
```
sudo -u USERNAME DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<UID>/bus notify-send
```
So my test script looks like this:
```
#!/bin/bash
in=$1
sudo -u user DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send "$in"
```
This could be added to FAQ.

**Comment by andy-portmen** [comment]
Nice! I am not sure if the `sudo -u user` is needed though. The extension is executing on the current user's desktop.

> This could be added to FAQ.

https://webextension.org/listing/external-application-button.html?rev#faq31

**Comment by ZaxonXP** [comment]
I tried without `sudo -u user` and it also works without it. So, you can update the FAQ.
