### ISSUE TITLE
How to make it target a flatpak installed browser?

### ISSUE THREAD

**Issue by noyannus** [andy-portmen/external-application-button#104]
What needs to be entered in the Options page to make a page from another browser open in a Flatpak installed browser? Notably Ungoogled-Chromium, but a general solution and an entry in the FAQ would be great!

**Comment by andy-portmen** [comment]
There is still no working solution for Flatpak. Somebody need to debug the [browser log](https://www.chromium.org/for-testers/enable-logging/) to find the new locations for the native client.

**Comment by noyannus** [comment]
This works for me now. 
KDE 6; Chromium: Version 124.0.6367.118 (Official Build, _ungoogled-chromium_) (64-bit)

---
**Application Setup**
Display Name 	`Open in Chromium (Flatpak)`
Executable Name 		`/usr/bin/flatpak`
Arguments 	`run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding io.github.ungoogled_software.ungoogled_chromium @@u [HREF] @@`

---
I see no reason why this should not work for other Flatpak Chrome derivatives. It would be useful to include it in the readme/FAQ or as a preset.

Closing as resolved.

----

P.S. I strongly suggest to rename the `Update Application` button. The label as it is now makes one think that an update for the current browser is to be downloaded. Use `Save Settings` or similar instead, that will be more widely understood.
