### ISSUE TITLE
Doesn't work with .ps1 or .bat scripts

### ISSUE THREAD

**Issue by Alfamari** [andy-portmen/external-application-button#105]
Doesn't play nice with custom scripts. Doesn't work at all with .ps1 PowerShell scripts and does some weird spam open-close with .bat scripts.
For Powershell, it keeps opening up the "One Last Step"/installation/debug page. The check connection passes. I confirmed the path was correct because I copied it and didn't type it, I even added the script to path and used the path environment variable, I ran the debugging flags and the logs are blank.

I'm using Vivaldi, dunno if that has anything to do with it. But it does open Notepad though.

**Comment by andy-portmen** [comment]
FAQ #10, https://webextension.org/listing/external-application-button.html

**Comment by Alfamari** [comment]
Damnit, sorry for wasting your time.
