### ISSUE TITLE
Where to put client files for use with Waterfox?

### ISSUE THREAD

**Issue by sonofevil** [andy-portmen/external-application-button#19]
I have the External Application Button addon installed in Waterfox 56.2.3 for Linux. After "successful" installation of the client, the Addon still reports `Cannot find the native client. Follow the 3 steps to install the native client`. Since part of the client is installed in `/.mozilla/native-messaging-hosts` I figure this may have something to do with it? The Waterfox equivalent to Firefox' `~/.mozilla/firefox` directory is found in `~/.waterfox`. Does this mean I have to move the file somewhere else?

Output of installer:
```
# sh install.sh
/usr/bin/node
NodeJS status = 0
Installer is using your system NodeJS.
 -> Root directory is /home/me/.config
 -> Creating a directory at /home/me/.config/google-chrome/NativeMessagingHosts
 -> Chrome Browser is supported
 -> Creating a directory at /home/me/.config/chromium/NativeMessagingHosts
 -> Chromium Browser is supported
 -> Creating a directory at /home/me/.config/vivaldi/NativeMessagingHosts
 -> Vivaldi Browser is supported
 -> Creating a directory at /home/me/.mozilla/native-messaging-hosts
 -> Firefox Browser is supported
 -> Creating a directory at /home/me/.config/com.add0n.node
 => Native Host is installed in /home/me/.config/com.add0n.node


>>> Application is ready to use <<<
```

**Comment by andy-portmen** [comment]
I am not sure if Waterfox supports native messaging.

**Comment by andy-portmen** [comment]
The native client support Waterfox browser; https://github.com/andy-portmen/native-client/search?q=waterfox&unscoped_q=waterfox

So I am closing this bug. Please update your native client.
https://github.com/andy-portmen/native-client/releases
