### ISSUE TITLE
[HREF] in context menu, do not send URL to MPV player 

### ISSUE THREAD

**Issue by Killogy** [andy-portmen/external-application-button#2]
I have set [HREF] in the context menu to send link URL to MPV player, worked until Versión 0.2.1, stopped working with Versión 0.2.2 and Versión 0.2.3 version. From toolbar is working.

Testing right clicking on **Ver programa** to send URL link to MPV player, nothing happens.  

http://www.mitele.es/programas-tv/las-mananas-de-cuatro/0000000020059/ 

Left clicking on **Ver programa** and then using right menu context options is working, every context option

I´m using latest firefox version Firefox 56.0 (64-bit)

**Comment by andy-portmen** [comment]
Version 0.2.3 works just fine for me. Can you create a new context menu item and retry? Open the options page and select the entry so that the extension fill all the fields. Now select "New" from the drop down and save as a new name.

**Comment by Killogy** [comment]
Does not works for me, I need to reinstall Versión 0.2.1, then I select application from addons page and press Update Application and it works, installing 0.2.2 or 0.2.3 and selecting application and Update Application does nor works, even creating it  as a new application doesn´t works

**Comment by andy-portmen** [comment]
What is your OS? Do you get any error in the console?

**Comment by Killogy** [comment]
Windows 7 64bit Firefox 56 (64 bit)

console:

"Something went wrong!

-----
Code: 2
Output: d:/Users/Killogy/AppData/Roaming/ACEStream/mpv/mpv/mpv.conf:4: unparseable extra characters: 'bestvideo[height<=?1080]+bestaudio/best'

Playing: http://www.mitele.es/programas-tv/las-mananas-de-cuatro/0000000020059/

[ytdl_hook] ERROR: Unsupported URL: http://www.mitele.es/programas-tv/las-mananas-de-cuatro/0000000020059

[ytdl_hook] youtube-dl failed, trying to play URL directly ... 

Failed to recognize file format.





Exiting... (Errors when loading file)


Error: "

**Comment by cubedj** [comment]
I'm not sure if it without some scripting will be possible to extract playable link for that page.. you need to at least pass the link for the player - which is "http://www.mitele.es/programas-tv/las-mananas-de-cuatro/59cce6e88bd4e5adbd8b4635/player" - that should with ytdl work just fine ... but direct link for m3u playlist would be best ([like this](https://miteleooyala-vh.akamaihd.net/i/9qazV1YzE6lTgtjMOv0UWDlNRJV_cR5f/,DOcJ-FxaFrRg4gtDEwOm84OjBrOz0bxa,DOcJ-FxaFrRg4gtDEwOjEwYjowODE7je,DOcJ-FxaFrRg4gtDEwOjFsaTowODE7WX,DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4,.csmil/index_0_av.m3u8?null=0&hdntl=exp=1506767967~acl=%2fi%2f9qazV1YzE6lTgtjMOv0UWDlNRJV_cR5f%2f,DOcJ-FxaFrRg4gtDEwOm84OjBrOz0bxa,DOcJ-FxaFrRg4gtDEwOjEwYjowODE7je,DOcJ-FxaFrRg4gtDEwOjFsaTowODE7WX,DOcJ-FxaFrRg4gtDEwOjJjcTowODE7R4,.csmil%2f*~data=hdntl~hmac=6b3b818348f283332b659cb392b74e22f17a5f033c3110826b9a399bd651e2c3))

**Comment by Killogy** [comment]
Addon was passing Link URL without problem until now, with addon versions 0.2.2-0.2.3 stopped working, just because that versions allow multiple context options, if Page Context and Link Context are checked, addon is sending Page URL instead Link URL, but if only Page URL is unchecked then addon send Link URL properly.

**Comment by andy-portmen** [comment]
> if Page Context and Link Context are checked, addon is sending Page URL instead Link URL

True! It should be fixed on 0.2.4

**Comment by andy-portmen** [comment]
It should be fixed on 0.2.4

**Comment by Killogy** [comment]
Thanx so much
