### ISSUE TITLE
Executable name for Windows Programs using Wine with Linux Mint

### ISSUE THREAD

**Issue by svendennis** [andy-portmen/external-application-button#20]
Hi,

what's the 'Executable name' for Windows programs using Wine on Linux Mint?

I got it working with native Linux programs (send link to Firefox) but not with any Windows programs  using Wine.

I've tried pretty much all possible paths that I can think of and double checked them in the command line in Terminal:

cd /home/user/.wine/drive_c/"Program Files (x86)"/Programfolder; wine program.exe

wine C:\\"Program Files (x86)"\\Programfolder\\program.exe\\

wine /home/user/.wine/"Program Files (x86)"/Programfolder/program.exe

all of them worked in the command line but not with the extension.

Thanks for your help!

**Comment by andy-portmen** [comment]
Try the "test arguments" button on the options page. You need to somehow have only one single argument which contains both path and the program name

This one seems okay to me:
```
wine "/home/user/.wine/Program Files (x86)/Programfolder/program.exe"
```
