### ISSUE TITLE
SELECTIONTEXT only returns the first word selected

### ISSUE THREAD

**Issue by elundmark** [andy-portmen/external-application-button#25]
Whenever I use [SELECTIONTEXT] and use it in scripts I only get the first word I selected in the browser.

__Example:__ If i select `Hello World` it only returns `Hello`
__Note:__ Yes I have the option _Surround arguments with quote characters_ selected.

Plugin v0.3.1
Firefox v68 64-bit
Ubuntu Linux 19.04 i3wm

**Comment by andy-portmen** [comment]
This works for me `"[SELECTIONTEXT]"` if selected text does not have `"` char. There is no need for the surround arguments... option to be checked

**Comment by elundmark** [comment]
Oh, I misunderstood that option totally, thank you for clarifying :+1:
