### ISSUE TITLE
Tab Context option missing

### ISSUE THREAD

**Issue by nevubm** [andy-portmen/external-application-button#26]
![eab](https://user-images.githubusercontent.com/14833020/63207368-a5260000-c092-11e9-8ef7-9e8c106924cf.png)

This is on Firefox Nightly

Previously defined apps with "Tab Context" still show in the tab menu. But the option can't be checked for new apps, unless created from a template of another app that already has it checked

**Comment by andy-portmen** [comment]
Thanks for the report. Will be fixed on the next release
