### ISSUE TITLE
Request: Ability to import/export configuration from Add-on options tab

### ISSUE THREAD

**Issue by 96fps** [andy-portmen/external-application-button#27]
It would be incredibly useful to be able to export/import the config as a human readable text file, or zip/directory of text files /icon images.

Firefox has reset my config on more than one occasion, so having a backup would be nice.

I use multiple machines, if the text config can be edited outside firefox (with a sanity check on import), I could write a script to keep the same settings but replace bin paths but keep the behavior.

**Comment by andy-portmen** [comment]
It is possible to create a JSON file on the options page to export the settings. You can use any text editor to alter the apps or add new ones.

**Comment by 96fps** [comment]
Thank you, I somehow missed that.
