### ISSUE TITLE
Cannot create item with duplicate id

### ISSUE THREAD

**Issue by lucknaumann** [andy-portmen/external-application-button#28]
Hi,
I've been getting this message for quite some time in the different browsers I use and have no idea what it means. I'm on Windows 10 v.1809 and using the latest versions of Chrome, FF, Vivaldi and EdgeDev Chromium. It happens regardless of which browser I open. 
Thanks.

**Comment by andy-portmen** [comment]
Can you provide steps to reproduce this?

**Comment by andy-portmen** [comment]
Should get fixed by the next release. Let me know if not.

**Comment by lucknaumann** [comment]
@andy-portmen OK - thanks. If it helps, I just opened whichever browser and upon opening, I would get several of the messages. However, it may be fixed because I haven't seen any recently. Thanks!

**Comment by andy-portmen** [comment]
> it may be fixed because I haven't seen any recently. 

Please reopen if you get the warning once again after updating to the latest release.

**Comment by lucknaumann** [comment]
Will do! Thanks! =)
