### ISSUE TITLE
Unable to play video using youtube-dl and VLC, using piping

### ISSUE THREAD

**Issue by afATRWTtdgsdfys** [andy-portmen/external-application-button#33]
Hi!	I've been meaning to play this video: http://vod.afreecatv.com/PLAYER/STATION/47364763 , a sky diving video, using youtube-dl as a means to stream the video to VLC.

The configuration for youtube-dl and VLC for External Application Button is as follows:

> Display Name: youtube-dl VLC
> Executable Name: C:\youtube-dl.exe
> Arguments: --get-url --format best [HREF] | C:\Program Files (x86)\VideoLAN\VLC\vlc.exe -

I didn't touch on the rest of the settings.

But upon launching the video through External Application Button, I got this error:

> Something went wrong!-----Code: 1Output: 
> http://videofile-hls-ko-upload-cf.afreecatv.com/afflv14/_definst_/save/afreeca/station/2019/0902/15/1567404925655973.smil/chunklist_w1488903444_b2000000_t64aGQyaw==.m3u8
> 
> Error: ERROR: '|' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:|" ) to search YouTube

I've tried opening the video using cmd:

`C:\youtube-dl.exe --get-url --format best http://vod.afreecatv.com/PLAYER/STATION/47364763 | "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" -`

and it had worked.

Is there a way to make this work with External Application Button?

Thank you!

**Comment by andy-portmen** [comment]
This is not a single command. You need to put the commands in a batch file and pass the path of the batch file instead
