### ISSUE TITLE
Context menu issues

### ISSUE THREAD

**Issue by nollinvoyd** [andy-portmen/external-application-button#34]
Previously, when I right clicked the toolbar button, I got the list of my media players, but no longer.

The page context sub menu only show the top two media players, when before it showed all.

I guess you already know about the missing tab context menu option.

**Comment by andy-portmen** [comment]
Please use the export button on the options page to create a JSON file and post it here. Hopefully, I can find the bug this way.

Then visit https://github.com/andy-portmen/external-application-button/issues/29 and see if the workaround applies for you or not.

**Comment by nollinvoyd** [comment]
@andy-portmen 
> 
> 
> Please use the export button on the options page to create a JSON file and post it here. Hopefully, I can find the bug this way.
> 
> Then visit #29 and see if the workaround applies for you or not.

It won't let me upload a JSON file

**Comment by andy-portmen** [comment]
zip the file first

**Comment by nollinvoyd** [comment]
I created a new profile and instead of importing the settings, I exported a fresh settings file. 

It's ok now.  Somehow the old settings file must have gotten corrupted.
