### ISSUE TITLE
context menu doesnt show for youtube checker

### ISSUE THREAD

**Issue by Joseph65** [andy-portmen/external-application-button#4]
i have this addon https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-checker/
which checks youtube new videos for a channel, but when i open the context menu to open with 
external application addon with mpv it doesnt show, It shows fine when im in the youtube page,
but in the addon youtube checker it doesnt show when i right click.

**Comment by andy-portmen** [comment]
WebExtension API is limited. It cannot be injected into other add-on pages. Sorry there is no workaround for this.
