### ISSUE TITLE
context menu on username textbox

### ISSUE THREAD

**Issue by gilles007-** [andy-portmen/external-application-button#41]
I don't know if this is  normal behavior or not.
But on websites i need to login, i don't have the context menu on username textbox.
Context menu is present for password textbox.
I'm trying to perform auto-type for keepass.

**Comment by andy-portmen** [comment]
> i don't have the context menu on username textbox.

You need to enable "Editable Context" option

**Comment by gilles007-** [comment]
I have check all but it don't show.
example : https://www.instagram.com/

**Comment by gilles007-** [comment]
I'm using addon 0.3.5

**Comment by gilles007-** [comment]
I tried this addon on another computer (firefox 76.0.1 x86 build) and got the same problem

**Comment by andy-portmen** [comment]
This looks like a FF bug. It works as expected on Chrome. Anyhow, in 0.3.7 release there is a new option to run a custom JS code before the external application is called. You can just add a context menu item for the page and use the pre-script to focus the username input before the KeePass application starts filling the credentials for you.

**Comment by gilles007-** [comment]
I don't think it's a FF bug because i have others addons which are working on a textbox.
I played with examples from FF and i can make a context menu on a textbox too.

**Comment by gilles007-** [comment]
could you please look at this : in options screen i have editable listed but in the code from common.js  there is not, i have a bookmark reference
`const pageContexts = contexts.filter(s => ['page', 'tab', 'selection', 'password', 'bookmark'].indexOf(s) !== -1);`
i don't know, where is editable in the code ?

**Comment by gilles007-** [comment]
I replaced with
`const pageContexts = contexts.filter(s => ['page', 'tab', 'selection', 'password', 'editable'].indexOf(s) !== -1);`
and now i have the context menu

**Comment by andy-portmen** [comment]
Thanks! It is fixed on 0.3.7.2 release.
