### ISSUE TITLE
The adon  stopped working in Linux FF  76.0.1

### ISSUE THREAD

**Issue by gerroon** [andy-portmen/external-application-button#43]
Hi

This add-on has been working fine for  me quite a while but today it stopped wortking suddenly not sure if this is because of a recent FF upgrade I did on Debian Testing to 76.0.1

thanks

**Comment by andy-portmen** [comment]
Please update to 03.7.2 release and reopen if you still have the issue

**Comment by gerroon** [comment]
Thanks, it works again after the update.
