### ISSUE TITLE
Addon stopped working with latest update.

### ISSUE THREAD

**Issue by KilliK69** [andy-portmen/external-application-button#44]
Hello.
Last  update 0.3.7 completely broke functionality.

I had version 0.3.4 which was working fine, but after the update, it stopped working. No external application starts. 

I uninstalled/reinstalled both the addon and the native client, but the problem remains.
I tried different external apps, with no arguments, just the full path and as a toolbar button. Nothing happens, there is not even an error message.
I reverted back to 0.3.4 but now I am getting the error message that the native client cant connect.

I run Windows 10 Pro 64bit build 1909 and Chrome 83.0.4103.61 (Official Build) (64-bit)

**Comment by andy-portmen** [comment]
There is a known issue with the v0.3.7 release. A new version is submitted to the Chrome Store but it takes a few days for Chrome to review new submissions.
