### ISSUE TITLE
Sending current URL to an external app (a bug?)

### ISSUE THREAD

**Issue by rg-software** [andy-portmen/external-application-button#45]
Hello,
I used External Application Button as a middleman for my own extension without any problems for some time, but it seems now I stumbled upon an error. Perhaps, it appeared with one of the recent updates (currently I have 0.3.7.2 installed). Here is my snippet:

```javascript
  chrome.tabs.query({'active': true, 'lastFocusedWindow': true}, function (tabs) {
    var cur_url = tabs[0].url;

    chrome.runtime.sendMessage('bifmfjgpgndemajpeeoiopbeilbaifdo', {
      app: {
        args: '[HREF]',
        path: 'MyCoolApp'
      },
      tab: {
        url: cur_url
      }
    });
  });
```

When this code executes, I get an error in External Application Button here:

common.js:376 
Error handling response: ReferenceError: frameId is not defined
in
execute(request.app, request.tab, request.selectionText, frameId);

Any clues?.. thanks!

**Comment by andy-portmen** [comment]
Thanks for the report. Will get fixed by 0.3.8 release.
