### ISSUE TITLE
Cannot use from other extension

### ISSUE THREAD

**Issue by axel0070** [andy-portmen/external-application-button#46]
I have the version 0.3.8 installed.

I created a very simple chrome extension wih one file:

```
// background.js

chrome.browserAction.onClicked.addListener(function() {
	console.log("CLIKED");
	
	chrome.tabs.query({'active': true}, function (tabs) {
		
		console.log("Getted tabs");
		var cur_url = tabs[0].url;

		chrome.runtime.sendMessage('bifmfjgpgndemajpeeoiopbeilbaifdo', {
		  app: {
			path: 'C:\Program Files\FileZilla FTP Client\filezilla.exe'
		  },
		  tab: {
			url: cur_url
		  }
		});
	  });
});
```

First time I launch it, I got a dialog window asking if I allow this extension, then each time I am clicking on the icon, the ~/data/helper/index.html page show up, showing the three steps striked, and when I am clicking on "check connection" it is green and valid.

I tried to use the system to open "C:\Program Files\FileZilla FTP Client\filezilla.exe" it worked. So it is not a problem with the path.

Here are the logs of my extension (nothing special..)
```
Background.js:4 CLIKED
Background.js:8 Getted tabs
```

**Comment by andy-portmen** [comment]
try 'C:\\Program Files\\FileZilla FTP Client\\filezilla.exe'

**Comment by andy-portmen** [comment]
also to see the actual error, take a look at the background page of the EAB.
