### ISSUE TITLE
Debain buster: Cannot find the native client

### ISSUE THREAD

**Issue by jsbien** [andy-portmen/external-application-button#49]
Installation looked succesfull:
` => Native Host is installed in /root/.config/com.add0n.node`

**Comment by andy-portmen** [comment]
is this on FF? if so open the browser console (Ctrl + Shift + J) and try to use the extension. You should get a log on the console about the issue.

**Comment by jsbien** [comment]
Yes, this is on FF.

The log says `ExtensionError: No such native application com.add0n.node`

The install log says:

`Native Host is installed in /root/.config/com.add0n.node`

I've copied the directory to my home .config and changed the ownership, but it not helped.

**Comment by andy-portmen** [comment]
Are you a root user? Where did the extension place the JSON file? It should be on `~/.mozilla/native-messaging-hosts/`

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location

**Comment by jsbien** [comment]
I apologize for a false alarm. Looks like by mistake I have run install as a root. Now it works.
