### ISSUE TITLE
Percent characters are considered as escape sequences, and get broken

### ISSUE THREAD

**Issue by AirQuick** [andy-portmen/external-application-button#5]
In the add-on options page, add an application with `Arguments` = `https://en.wikipedia.org/wiki/Bront%C3%AB_family`. The URL should take you to a page of `Brontë family`.

But when you invoke this application, External Application Button 0.2.7 does not pass this argument as is. Instead, it produces an argument of `https://en.wikipedia.org/wiki/BrontÃ«_family`.

**Comment by andy-portmen** [comment]
Thanks for the report. It will be fixed on the next release.

**Comment by AirQuick** [comment]
Thanks for the fix!
Could you please consider releasing it? I'm encountering the issue several times a day.

**Comment by andy-portmen** [comment]
The new version is released.
