### ISSUE TITLE
A problem with Edge and DjVu

### ISSUE THREAD

**Issue by jsbien** [andy-portmen/external-application-button#55]
I don't use Edge, I made a quick test of DjVu access just of curiosity. It works with the menu, but not with just clicking.

When configuring and selecting "Navigation", I was asked for the permission "Odczytywanie i zmienianie wszystkich danych na odwiedzanych witrynach" meaning reading and changing all data on visited sites. However when configuring for Firefox I was asked for two permission. One is "Acces your data for all websites" which seems to me equivalent to the one quoted above. The second is "Access browser activity during navigation". Perhaps the lack of this second one is the culprit?

**Comment by andy-portmen** [comment]
Different browsers show different permission notifications, that's fine. 

> . It works with the menu, but not with just clicking.

Make sure you have refreshed the page.

**Comment by andy-portmen** [comment]
reopen if you still have the issue
