### ISSUE TITLE
Problem reinstalling native client

### ISSUE THREAD

**Issue by jsbien** [andy-portmen/external-application-button#59]
On a new computer the extension was working with Firefox but not with Chrome. So I tried to reinstall the native client, now none of them works. I enclosed the installation log.
[bad-install.log.gz](https://github.com/andy-portmen/external-application-button/files/5623968/bad-install.log.gz)

**Comment by andy-portmen** [comment]
`Error: ETXTBSY: text file is busy, open '/home/jsbien/.config/com.add0n.node/node'`

Seems like the extension cannot overwrite files.

**Comment by andy-portmen** [comment]
close all editor instances and run `sudo killall node`

**Comment by jsbien** [comment]
Thanks. Now again Firefox works but Chrome cannot find the native client. Do I understand correctly that the same client can be used by both browsers?

**Comment by andy-portmen** [comment]
>  Chrome cannot find the native client

Get the original file and and rerun the installer. Also make sure the custom ID is added to the Chrome if you are using the developer version of the extension.

**Comment by jsbien** [comment]
Nothing changed (I test the original version).

**Comment by andy-portmen** [comment]
What is the ID of the the extension in `chrome://extensions`

**Comment by jsbien** [comment]
Sorry for the false alarm, I just confused the extensions :-( So how to change the name of my version to avoid such mistakes in the future?

**Comment by andy-portmen** [comment]
go to the `manifest.json` and change the name, description, ...
Also move `"webNavigation"`, `"*://*/*"` to the permissions section.

```
  ...
  "permissions": [
    "activeTab",
    "storage",
    "menus",
    "nativeMessaging",
    "downloads",
    "bookmarks",
    "notifications",
    "webNavigation",
    "*://*/*"
  ],
  "optional_permissions": [],
  ...
```

**Comment by andy-portmen** [comment]
> Also move "webNavigation", "*://*/*" to the permissions section.

might not work in FF.

**Comment by jsbien** [comment]
OK, I will try.
