### ISSUE TITLE
Firefox - "enabling console logs" links to Chromium documentation

### ISSUE THREAD

**Issue by Luke-Baker** [andy-portmen/external-application-button#6]
Set up a button to an application that doesn't exist in order to get to `moz-extension://…/data/helper/index.html`. On that page, there's an "enabling console logs" link which points to `https://www.chromium.org/for-testers/enable-logging`

It should point to something for Firefox users, probably `https://developer.mozilla.org/docs/Tools/Browser_Console`

**Comment by andy-portmen** [comment]
Thanks for the report.
