### ISSUE TITLE
How to use [POST_SCRIPT_STDOUT]?

### ISSUE THREAD

**Issue by hhaoao** [andy-portmen/external-application-button#65]
I printed the three keywords`[POST_SCRIPT_CODE], [POST_SCRIPT_STDOUT], and [POST_SCRIPT_STDERR]` directly and found that only [POST_SCRIPT_CODE] returned 0.

```js
alert([POST_SCRIPT_CODE])
```

**Comment by andy-portmen** [comment]
Try
```js
console.log([POST_SCRIPT_CODE], `[POST_SCRIPT_STDOUT]`, `[POST_SCRIPT_STDERR]`)
```

**Comment by hhaoao** [comment]
Oh, the result of this keyword is inconsistent with what I expected.I thought it was returning the result of bat running(Like the following command, what I want is to get the url), but it was just printing the bat script.


```console.log(`[POST_SCRIPT_STDOUT]`);```, error result:
```js

C:UsersAdministratorAppDataLocalcom.add0n.node>D:msys64msys2_shell.cmd -mingw64 -c "youtube-dl --get-url http://localhost:8000/" 
```

expected result:
```bat
http://localhost:8000/test.mp4
```

**Comment by andy-portmen** [comment]
On my setup, I get the following output on https://www.w3schools.com/html/html5_video.asp

<img width="827" alt="one" src="https://user-images.githubusercontent.com/6779535/128601630-02ab9a65-c295-411e-8f06-8104bb967d60.png">

Executable Name: `/usr/local/bin/python3`
Arguments: `/Users/.../youtube-dl --get-url [HREF]`
Post JS: 
```js
console.log([POST_SCRIPT_CODE], `[POST_SCRIPT_STDOUT]`, `[POST_SCRIPT_STDERR]`)
```

**Comment by andy-portmen** [comment]
> Is there a way to get chrome.runtime.sendNativeMessage response?

See https://github.com/andy-portmen/external-application-button/blob/master/firefox/common.js#L120-L122

**Comment by hhaoao** [comment]
Thank you for your patience, but I still don't know how the program in the command line in the windows system outputs the results to stdout.

The only successful example: ```echo "hello world" ```

Display Name: `Sniff Video`
Executable Name: `C:\Windows\System32\cmd.exe`
Arguments: `/s /c f:\test.bat`
Post JavaScript: ```console.log(`[POST_SCRIPT_STDOUT]`, `[POST_SCRIPT_STDERR]`);```
Quotation: `[yes]`Surround arguments with quote characters

test.bat content:
```bat
echo "hello world"
```

**Comment by andy-portmen** [comment]
you need to force the command to print to `stdout`

```batch
@echo off

for /f %%O in ('tree D:/') do (echo %%O)
```

**Comment by hhaoao** [comment]
Thank you very much, it works perfectly now.

material:
[`for /f` doc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)

[post_script_example.zip](https://github.com/andy-portmen/external-application-button/files/6950982/post_script_example.zip)

**Comment by hhaoao** [comment]
postscipt example:
```js
var url = `[POST_SCRIPT_STDOUT]`;
var unordered_list = '<ul><li><h5><a href=' + url + '>youtube-dl return\'s url</a></h5></li></ul>';
var list_div = document.createElement('div');
list_div.id = 'cat_list_div';
list_div.style.position = 'fixed'; 
list_div.style.top = '5%';
list_div.style.right = '5%';
list_div.innerHTML = unordered_list;
list_div.style.display="";

document.body.appendChild(list_div);
```
