### ISSUE TITLE
Feature Request: Add trigger actions besides toolbar button press

### ISSUE THREAD

**Issue by e-t-l** [andy-portmen/external-application-button#70]
Would it be possible to add "listeners" for various browser actions to act as a trigger for the external application, so the user doesn't have to click the toolbar button each time? (e.g. opening a certain external app every time a download is initiated)

**Comment by Ashbd9** [comment]
I also would like this feature such as passing an opened link to an external program if it is from a chosen website.

**Comment by andy-portmen** [comment]
https://webextension.org/listing/external-application-button.html?rev#faq32
