### ISSUE TITLE
Context submenu disappears randomly

### ISSUE THREAD

**Issue by detuur** [andy-portmen/external-application-button#75]
This issue started appearing relatively recently, in the past couple of weeks.

### Description of the issue:

- On a web page, any page, right click on a link that you want to open with an external application.
- Notice the submenu for the external application button is missing.
- Enter the extension's Options page (`moz-ext://somehash`, not `about:addons`). Just opening that page is enough.
- The submenu is now back and operational. It will stay there, even across restarts, until in some future session (hours, days later?) it disappears again.

### Steps to reproduce
Tricky. I'm not sure exactly when the submenu disappears, as I only use it once or twice a week, if that. It's possible updates to Firefox cause it to happen.

### Environment
- OS: Windows 10, Version 21H2 (OS Build 19044.2006)
- Firefox:
    - Update channel: `beta` (Firefox Developer Edition)
    - Version: 106.0b9 (64-bit)
    - Build ID: 20221006191955

**Comment by SAJewers** [comment]
Been seeing this issue on Nightly for a week or so now. Unfortunately, the above workaround does not work in the latest Nightly.

**Comment by andy-portmen** [comment]
Wait for the `0.5.1` release and let me know if it is fixed or not.

**Comment by SAJewers** [comment]
Seems to be fixed for me now. Thanks!

**Comment by detuur** [comment]
Fixed indeed. Thanks!
