### ISSUE TITLE
[request] Sort profiles alphabetically

### ISSUE THREAD

**Issue by stax76** [andy-portmen/external-application-button#80]
This would also allow a custom sort order when users use a special profile name prefix:

`AA - `
`ZZ - `

`11 - `
`99 - `

**Comment by stax76** [comment]
I changed how I use the extension and after that no longer need the feature.

**Comment by kargaroc** [comment]
I still think this would be a good feature to have.

**Comment by hombre12345** [comment]
> This would also allow a custom sort order when users use a special profile name prefix:
> 
> `AA - ` `ZZ - `
> 
> `11 - ` `99 - `

<details><summary>Details</summary>
<p>



</p>
</details>
