### ISSUE TITLE
[REFERRER][USERAGENT][COOKIE] return blank value in Firefox

### ISSUE THREAD

**Issue by GunGunGun** [andy-portmen/external-application-button#84]
Just that, and I believe many [] features are broken in Firefox, including my previous issue about [PRE_SCRIPT] returns undefined.

My Firefox version 106, External Application Button latest.

**Comment by GunGunGun** [comment]
It looks like updated to latest version solved this issue.

**Comment by GunGunGun** [comment]
Actually, reopen this Issue because even with latest Firefox and latest External Application Button, [REFERRER] is still not working, I recorded a video: https://gfycat.com/GloomyTornKoala

**Comment by andy-portmen** [comment]
`[REFERRER]` is `document.referrer`. I guess what you need is `location.href`.

**Comment by GunGunGun** [comment]
> `[REFERRER]` is `document.referrer`. I guess what you need is `location.href`.

Yeah, using [PRE_SCRIPT] solves the problem, but it some cases I think it's still better to use both [REFERRER] and [PRE_SCRIPT] to get both Referer and something else, for example title.

Can you add ability to use multiple [PRE_SCRIPT]s like [PRE_SCRIPT_1] to [PRE_SCRIPT_99], basically with array variable. For example:

```
document.currentScript.output = [document.referer, document.title, document.href]
```

then in Arguments:

`--title="[PRE_SCRIPT_2]" --referer="[PRE_SCRIPT_1]" --alternativelink="[PRE_SCRIPT_3]" [HREF]`

**Comment by andy-portmen** [comment]
Why not! Update to `0.5.3` and use `[PRE_SCRIPT:0]`, `[PRE_SCRIPT:1]`, ... keywords

**Comment by GunGunGun** [comment]
> Why not! Update to `0.5.3` and use `[PRE_SCRIPT:0]`, `[PRE_SCRIPT:1]`, ... keywords

Thank you! This is golden!!! Love it!
