### ISSUE TITLE
DOWNLOADED_PATH points to incorrect path

### ISSUE THREAD

**Issue by drventure** [andy-portmen/external-application-button#97]
Hi

I've installed External App Button on Win11 64bit with Edge, and the install all went smoothly, but it's not working.
What happens I've configured a app to use the [DOWNLOADED_PATH] option, and that works, the clicked link is automatically downloaded and the target application is loaded, except
the file is downloaded to "%USERPROFILE%\Downloads\filename", ie the default download folder for Edge
but when the target app is started, it's passed a filename of "%USERPROFILE%\AppData\Local\com.add0ns.node\filename" and of course the app fails to load the file because that's the wrong location.

I had an earlier version installed on a different machine running win10 and it worked perfectly, so I'm not sure whether the issue is the later version of External App Button, or the fact that it's running under Win11 edge.

Is there anything I can do to help debug the issue, or maybe something that I could have missed while installing?

Thanks!

**Comment by andy-portmen** [comment]
Ask the extension to print the path to a file to debug. This `\AppData\Local\com.add0ns.node\...` usually means the external application tries to resolve the path from current directory.

**Comment by drventure** [comment]
Thank you so much!
With that tip, i went back and reread the help page and saw the mention of creating a little bat file to see the args.
From there it was obvious that I needed to put the [DOWNLOADED_PATH} argument in double quotes.
That fixed it completely.

Thanks again!
